### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by sourabhtk37**
A format for proposing the talk is added.

### CODE REVIEW

**Comment by sourabhtk37** [comment]
@mysticTot please confirm.

**Comment by mysticTot** [comment]
Please do mention these things
>Slides are mandatory
>Folks can also submit proposal for dev-sprints

**Comment by mysticTot** [comment]
brief intro about talk/workshop with  *prerequisites*

**Comment by sourabhtk37** [comment]
Do we have to make slides mandatory? Since some talks are pure handson and doesn't require slides et all.

**Comment by sourabhtk37** [comment]
There is abstract and prerequisite section in the template.

**Comment by mysticTot** [comment]
yes we would need slides most of the times to create content.

**Pull request merged**
