### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sourabhtk37**
Added slides for the talks for which slides were present.

### CODE REVIEW

**Comment by sourabhtk37** [comment]
cc: @Warlord77 @mysticTot

**Comment by mysticTot** [comment]
Thanks for working on this. 
Shouldn't we add a new file named talks-log where we can put all these things so that  user don't have to read the entire README.md file and further, with this approach the file will grow longer and longer. 
I think introducing a new file will make it more modular. what say?

**Comment by sourabhtk37** [comment]
That would mean one more step to see the list of talks. The README seemed empty for the new users, that's why I filled it in. It is followed by others too.

How are we gonna structure the files in case of `talks-log`?

**Comment by sourabhtk37** [comment]
Or we can make a static site for it using a generator.

**Comment by mysticTot** [comment]
See if we create make  a new file `talks-log`.
                 talks
                       |-- README.md                          #contains link for new issue and talks-logs
                       `-- talks-log                                  # list of past talks and slides
This would be more structured.
Over a span of time, talk list will grow and it would look untidy if we put list of past talks in README.

Idea of static site looks good. So how can we proceed this?

**Comment by sourabhtk37** [comment]
So we provide links to the talks log readme as:
```
### 2017
- March/date meetup (<- link to the talks-log of march file)
- april/date meetup (<- link)

and so on...

**Comment by sourabhtk37** [comment]
static site would need a work since it would require people to oblige to the format inorder to completely automate it.

**Comment by sourabhtk37** [comment]
Added the changes @mysticTot

**Comment by mysticTot** [comment]
Sorry, I was bit busy.
Thanks a lot Tk.
Now merged.

**Comment by mysticTot** [comment]
Thanks for working on it

**Pull request merged**
